sudo: false

env:
  secure: "Alok/RlSD1dwHMmfTRCKyhLsIDsvi+s/2ct8MY6yKgn8QruqfJQcJ0FXtxgvi5gtLctPqR07RbcO+cnYBhCzOH5elzSCYNOOkijqBDVyejkUhJ9DtALmb+2FAvGQsTIEeFyJdHCl3wZIo3ieDHmFljyugLwjUE86UsBJ4aD9amqNsokYnIab83b7yXNgjwEZWoyiFqdlhCsFXizwdUiOvggUNuaFXHiR2+stxngAXr6G1Ulc28ZIl8n7f9vH0X5KUl2wJe6H6izGdhkM+O2+7aPwsxs6mlhZdE3zwxIETGMEtnLkdLH1HobrGQvXxMz5NZ1FdFPGTxOmaBl+xr0rvYsIm3tibQHFchsBCczUV7UKW8fEfImXX2uHVsXCxYN+4JYH6+QAJeXuOUqF3aUASvnQlCIQvnQJ5SPKVxhmO71ZGnVoHMxKIS9FkmMe6IaYIi2gFXMhH+LSULKmCRJ5AiVnW2dmMSHe7F8vT1P+52YVMzq8f7oeQzIabVk1QZjEulnoFdzraVjoXt+X4dt61HxDtnpsxTVQjwujMvuVgGM2e6+gXZYjsfcrd+ghdHPYYAduQ+9rtimLbj5cypeMd9n6ba5j5PFv9N2zrGhuQy91T8pl2TEKwnBcUtEXYyIqUEZRZFjSsCjT4EO+3DjjITiLLOHh7HtFi6c0o6Mebrs="

language: java

jdk:
  - openjdk8

before_deploy:
  - git clone --depth 1 --branch benchmark-results https://github.com/neo4j-contrib/neo4j-graph-algorithms.git benchmark/results
  - rm -rf benchmark/results/.git
  - rm benchmark/results/deployed*
  - mvn -DskipTests -PBenchmark -pl benchmark package
  - java -jar benchmark/target/benchmark.jar -jvmArgs "-server -d64 -Xmx4g -Xms4g" -prof gc -rf csv -rff benchmark/results/b${TRAVIS_BUILD_NUMBER}-${TRAVIS_COMMIT}-$(date '+%Y-%m-%dT%H-%M-%S').csv -e 'Ldbc'

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GHTOKEN
  local_dir: benchmark/results
  target_branch: benchmark-results
  on:
    branch: 3.1

# block benchmark results from building in travis
branches:
  except:
  - benchmark-results
